modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/bonsaistudi0s/endermanoverhaul/issues"

[[mods]]
modId = "endermanoverhaul"
version = "${version}"
displayName = "Enderman Overhaul"
displayURL = "https://modrinth.com/mod/enderman-overhaul"
logoFile = "icon.png"
authors = "Alex Nijjar, Joosh"
credits = ""
description = "Enderman overhaul adds biome-specific Enderman!"

[[dependencies.endermanoverhaul]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endermanoverhaul]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endermanoverhaul]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endermanoverhaul]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endermanoverhaul]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2.2,)"
ordering = "NONE"
side = "BOTH"